name: Publish
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Setup .npmrc with authentication
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm config set registry https://registry.npmjs.org/
          npm config set always-auth true
      
      - name: Debug - Check .npmrc content
        run: |
          echo "Contents of .npmrc:"
          cat ~/.npmrc | sed 's/_authToken=.*/_authToken=***HIDDEN***/'
          echo "NPM config:"
          npm config list
      
      - name: Debug - Verify authentication
        run: |
          echo "Checking npm authentication:"
          npm whoami
          echo "Checking package ownership:"
          npm owner ls usagey
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Build
        run: npm run build
      
      - name: Get current package version
        id: current_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      
      - name: Get published version
        id: published_version
        run: |
          PUBLISHED_VERSION=$(npm view usagey version 2>/dev/null || echo "0.0.0")
          echo "version=$PUBLISHED_VERSION" >> $GITHUB_OUTPUT
      
      - name: Compare versions
        id: version_check
        run: |
          CURRENT="${{ steps.current_version.outputs.version }}"
          PUBLISHED="${{ steps.published_version.outputs.version }}"
          echo "Current version: $CURRENT"
          echo "Published version: $PUBLISHED"
          
          if [ "$CURRENT" != "$PUBLISHED" ]; then
            echo "should_publish=true" >> $GITHUB_OUTPUT
            echo "New version detected - will publish"
          else
            echo "should_publish=false" >> $GITHUB_OUTPUT
            echo "No version change - skipping publish"
          fi
      
      - name: Publish to npm with explicit registry
        if: steps.version_check.outputs.should_publish == 'true'
        run: npm publish --registry https://registry.npmjs.org/ --access public