name: Version Bump

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to bump to (major.minor.patch)'
        required: true
        type: string

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    - name: Update version
      run: npm version ${{ github.event.inputs.version }} -m "Bump version to %s"
    - name: Push changes
      run: |
        git push
        git push --tags